spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fyg?useSSL=false
    username: entrydemo
    password: password
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#logging:
#  level:
##    org.springframework: DEBUG
#    org.hibernate: DEBUG

